---
title: "QUALISALVADOR: Vegetação e Temperatura de superfície (2016-2020)" 
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(flexdashboard)
library(sf)
library(tmap)
library(tidyverse)
library(googlesheets4)
library(plotly)
library(zoo)
library(hrbrthemes)

```

```{r get-data, message=FALSE, include=FALSE}


```

```{js}

document.addEventListener("DOMContentLoaded", function(){
    $('a[data-toggle="tab"]').on('click', function(e){
      // find the tab index that is click
      child = e.target.parentNode;
      tabnum = Array.from(child.parentNode.children).indexOf(child);
      // find in which column we are
      column = $(e.target).closest("div[id]");
      // show the same tab in the other column
      columnid = column.attr("id");
      if (columnid == "column") {
        columnto = "column-1";
});
```

Column { .tabset data-width=600}
-----------------------------------------------------------------------
### Cobertura Vegetal

```{r}

veg_qualis = read_sf("CobVeg_L8_2013_2016_2019_bairros.shp")

veg_qualis$set16mean = veg_qualis$set16mean*100

names(veg_qualis)[names(veg_qualis) == 'set16mean'] <- '% de Cobertura Vegetal'

names(veg_qualis)[names(veg_qualis) == 'NM_BAIRROS'] <- 'Bairro'

intervalos <- c(0, 8, 14, 22, 30, 46)
 
mapa <- 
  tm_shape(veg_qualis) +
  tm_polygons(col ="% de Cobertura Vegetal", 
              style="fixed",
              breaks = intervalos,
              textNA = "Sem informação",
              palette = "BuGn",
              id="Bairro",
              title="Proporção de cobertura vegetal (%)") +

  tm_layout(legend.format = list(text.separator = "-"))


mapa

tmap_mode("view")
tmap_last()


```

### Cobertura Vegetal

```{r}

tst_qualis = read_sf("TST_2013_2019_bairros.shp")

tst_qualis$set16mean = tst_qualis$set16mean

names(tst_qualis)[names(tst_qualis) == 'set16mean'] <- 'Temperatura de superfície'

names(tst_qualis)[names(tst_qualis) == 'NM_BAIRROS'] <- 'Bairro'

intervalos <- c(25.2, 27.2, 29.1, 31.6, 33.8)
 
mapa1 <- 
  tm_shape(tst_qualis) +
  tm_polygons(col ="Temperatura de superfície", 
              style="fixed",
              breaks = intervalos,
              textNA = "Sem informação",
              palette = "BuGn",
              id="Bairro",
              title="Temperatura de superfície") +

  tm_layout(legend.format = list(text.separator = "-"))


mapa1

tmap_mode("view")
tmap_last()


```

Column {data-width=400 .tabset}
-----------------------------------------------------------------------

### Gráfico: Cobertura vegetal

```{r}

veg_qualis_grafico = veg_qualis

grafico1 <- ggplot(veg_qualis_grafico, aes(x = `Bairro`, y = `% de Cobertura Vegetal`)) + 
  
  geom_bar(stat="identity", color="blue", fill="white") +
  ggtitle("Cobertura Vegetal")+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  labs(x = "Bairros", y = "%")

ggplotly(grafico1)

```

### Gráfico: Temperatura de Superfície

```{r}

tst_qualis_grafico = tst_qualis

grafico1 <- ggplot(tst_qualis_grafico, aes(x = `Bairro`, y = `Temperatura de superfície`)) + 
  
  geom_bar(stat="identity", color="blue", fill="white") +
  ggtitle("Temperatura de superfície")+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+
  labs(x = "Bairros", y = "%")

ggplotly(grafico1)

```
